### ISSUE TITLE
Unable to checkin artifacts

### ISSUE THREAD

**Issue by JPGRodrigues** [jessehouwing/vsts-tfvc-tasks#15]
System.Management.Automation.MethodInvocationException: Exception calling "EvaluateCheckin2" with "6" argument(s): "The array must contain at least one element.

Parameter name: changes" ---> System.ArgumentException: The array must contain at least one element.

Parameter name: changes

at Microsoft.TeamFoundation.Common.TFCommonUtil.CheckArrayForNullOrEmpty[T](T[] array, String arrayName)

at Microsoft.TeamFoundation.VersionControl.Client.Workspace.EvaluateCheckin2(CheckinEvaluationOptions options, IEnumerable`1 allChanges, IEnumerable`1 changes, String comment, CheckinNote checkinNote, WorkItemCheckinInfo[] workItemChanges)

at CallSite.Target(Closure , CallSite , Object , Object , Object , Object , Object , Object , WorkItemCheckinInfo[] )

--- End of inner exception stack trace ---

at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)

at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)

at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)

at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)

at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)

at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()

at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by jessehouwing** [comment]
Looks like no changes were detected. Are there changed files when calling the task?

**Comment by jessehouwing** [comment]
Please verify with the latest build

**Comment by JPGRodrigues** [comment]
Love the fix... 
If there is no item to checkin, then there is no error!
Thank you,João Paulo

Date: Mon, 22 Feb 2016 01:30:11 -0800

**Comment by JPGRodrigues** [comment]
With the new build, there is no error when no updates are needed!
Thank you.

**Comment by jessehouwing** [comment]
I just released a major update of the tasks, which adds auto-detect changes to the Checkin task. Would love to get your feedback.
