### ISSUE TITLE
unsupported characters ń

### ISSUE THREAD

**Issue by tomkor** [jessehouwing/vsts-tfvc-tasks#46]
2017-04-04T05:18:08.3136085Z ##[section]Starting: Check changes into source control
2017-04-04T05:18:08.3136085Z ==============================================================================
2017-04-04T05:18:08.3136085Z Task         : TFVC - Check-in changes 
2017-04-04T05:18:08.3136085Z Description  : Checks in any files changed in the repository.
2017-04-04T05:18:08.3136085Z Version      : 1.1.1297
2017-04-04T05:18:08.3136085Z Author       : Jesse Houwing
2017-04-04T05:18:08.3136085Z Help         : Version: 1.1.1297. [More Information](https://github.com/jessehouwing/vsts-tfvc-tasks/wiki/Check-in)
2017-04-04T05:18:08.3136085Z ==============================================================================
2017-04-04T05:18:08.3292350Z Preparing task execution handler.
2017-04-04T05:18:09.0011431Z Executing the powershell script: C:\AGENT\_work\_tasks\TFVCCheckin_31f040e5-e040-4556-878a-59a47c7128bd\1.1.1297\TfvcCheckin.ps1
2017-04-04T05:18:11.6418941Z $/eAuto/eAuto_app/eAuto_app/Properties/AssemblyInfo.cs
2017-04-04T05:18:15.9858513Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "CheckIn" with "1" argument(s): "TF10158: The user or group name Tomasz Korczy?ski contains unsupported characters, is empty, or too long." ---> Microsoft.TeamFoundation.VersionControl.Client.IllegalIdentityException: TF10158: The user or group name Tomasz Korczy?ski contains unsupported characters, is empty, or too long. ---> System.Web.Services.Protocols.SoapException: TF10158: The user or group name Tomasz Korczy?ski contains unsupported characters, is empty, or too long.
2017-04-04T05:18:15.9858513Z    --- End of inner exception stack trace ---
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.HandleReply(TfsClientOperation operation, TfsMessage message, Object[]& outputs)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.VersionControl.Client.Repository5.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, Failure[]& conflicts, Failure[]& failures, Boolean deferCheckIn, Int32 checkInTicket, Int32 maxClientPathLength)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.VersionControl.Client.WebServiceLayerLocalWorkspaces.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, UploadedBaselinesCollection uploadedBaselinesCollection, Failure[]& conflicts, Failure[]& failures, Boolean deferCheckIn, Int32 checkInTicket)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.PagedCheckin(IEnumerable`1 changes, Boolean changesIsAllPendingChanges, Changeset changeset, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, UploadedBaselinesCollection uploadedBaselinesCollection, Failure[]& conflictsArray, Failure[]& failuresArray)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckInInternal(WorkspaceCheckInParameters parameters, Int32 operationId)
2017-04-04T05:18:15.9858513Z    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckIn(WorkspaceCheckInParameters checkinParameters)
2017-04-04T05:18:15.9858513Z    at CallSite.Target(Closure , CallSite , Object , Object )
2017-04-04T05:18:15.9858513Z    --- End of inner exception stack trace ---
2017-04-04T05:18:15.9858513Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-04-04T05:18:15.9858513Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-04-04T05:18:15.9858513Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-04-04T05:18:15.9858513Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-04-04T05:18:15.9858513Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-04-04T05:18:16.0483547Z ##[error]PowerShell script completed with 1 errors.
2017-04-04T05:18:16.0483547Z ##[section]Finishing: Check changes into source control

**Comment by jessehouwing** [comment]
Hmz. That seems to fail at the soap level, meaning the standard libraries
are not handling the escaping correctly. Can you verify that you can check
in from the commandline using tf.exe? The powershell code closely mimics
that utility, and I don't remember any special handling in the author
property.

Will need to dig a bit. I'll get back to you.

**Comment by rdeldad** [comment]
Are there any updates on this issue?  We have just upgraded to TFS 2017 Update 1 and I am now receiving the same error (See Below).  Thanks.

-------------------

2017-04-22T18:01:02.8547380Z Set workingFolder to default: C:\TfsBuildAgents\ADCWin10_01\tasks\TFVCCheckin\1.1.1297
2017-04-22T18:01:02.8703618Z Executing the powershell script: C:\TfsBuildAgents\ADCWin10_01\tasks\TFVCCheckin\1.1.1297\TfvcCheckin.ps1
2017-04-22T18:01:03.7766161Z $/Osmose/Data_Collection_Tools/Main/Source/UWP_Apps/OsmoseDCT/Package.appxmanifest
2017-04-22T18:01:04.8234962Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "CheckIn" with "1" argument(s): "**TF10158: The user or group name Colligan, Rob contains unsupported characters, is empty, or too long."** ---> Microsoft.TeamFoundation.VersionControl.Client.IllegalIdentityException: TF10158: The user or group name Colligan, Rob contains unsupported characters, is empty, or too long. ---> System.Web.Services.Protocols.SoapException: TF10158: The user or group name Colligan, Rob contains unsupported characters, is empty, or too long.
2017-04-22T18:01:04.8391177Z ##[error]   --- End of inner exception stack trace ---
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.HandleReply(TfsClientOperation operation, TfsMessage message, Object[]& outputs)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.VersionControl.Client.Repository5.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, Failure[]& conflicts, Failure[]& failures, Boolean deferCheckIn, Int32 checkInTicket, Int32 maxClientPathLength)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.VersionControl.Client.WebServiceLayerLocalWorkspaces.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, UploadedBaselinesCollection uploadedBaselinesCollection, Failure[]& conflicts, Failure[]& failures, Boolean deferCheckIn, Int32 checkInTicket)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.PagedCheckin(IEnumerable`1 changes, Boolean changesIsAllPendingChanges, Changeset changeset, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, UploadedBaselinesCollection uploadedBaselinesCollection, Failure[]& conflictsArray, Failure[]& failuresArray)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckInInternal(WorkspaceCheckInParameters parameters, Int32 operationId)
2017-04-22T18:01:04.8391177Z ##[error]   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckIn(WorkspaceCheckInParameters checkinParameters)
2017-04-22T18:01:04.8391177Z ##[error]   at CallSite.Target(Closure , CallSite , Object , Object )
2017-04-22T18:01:04.8391177Z ##[error]   --- End of inner exception stack trace ---
2017-04-22T18:01:04.8391177Z ##[error]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-04-22T18:01:04.8391177Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-04-22T18:01:04.8391177Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-04-22T18:01:04.8391177Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-04-22T18:01:04.8391177Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by jessehouwing** [comment]
There have been issues with `, ` in user names and TFVC. my plans are to
rebuild the extension on top of the 2017 tf.exe. No deadline yet. If you're
willing to debug and submit a pull request, I'd really appreciate that.

**Comment by rdeldad** [comment]
Thank you for getting back to me so quickly!  

Unfortunately, since this is our production environment I won't be able to help debug the issue.  But the good news is that I have found an easy work around (and way to recreate).   I went into my TFS User Profile and changed my display name to be **First Last** instead of **Last, First** and the extension ran like a champ.   Hopefully others can use this as a work around until you can update the extension.

**Comment by jessehouwing** [comment]
It feels like a regression in TFS... Will ping someone on the vc team.

**Comment by jessehouwing** [comment]
From Microsoft, can you please supply any useful info you can get your hands on? 

> There have been identity related changes to TFS/VSTS in the past year.

> I do recall an issue several months back where a team had a : or ; in their name which became recently disallowed.  But that’s because those characters where special separators.  I’m not aware of any issues with normal Unicode characters.

 

> Is the identity that’s hitting this error already a known identity to TFS or to the AD domain? Ie, can you view changeset history and see their display name?  is just checkin failing?

> Can you look for errors in the event log?

**Comment by rdeldad** [comment]
So far I have not seen any other errors or impacts with changing the Display name.  When I look at the history, the changesets I had checked in now reflect the updated display name (**First Last**).  We are using AD for our identities

As for the error log, the only thing I see is the errors that were thrown by the extension.   Below is one of example of that error.

`Log Name:      Application
Source:        TFS Services
Date:          4/22/2017 2:01:04 PM
Event ID:      3000
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TFSAPP02.local.osmose.com
Description:
TF53010: The following error has occurred in a Team Foundation component or extension:
Date (UTC): 4/22/2017 6:01:04 PM
Machine: TFSAPP02
Application Domain: /LM/W3SVC/2/ROOT/tfs-13-131373509863410586
Assembly: Microsoft.TeamFoundation.Framework.Server, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
Service Host: 1dc4e278-6813-4749-90b3-0947408ef09b (Osmose)
Process Details:
  Process Name: w3wp
  Process Id: 3800
  Thread Id: 3472
  Account name: 35deb4eb-8d0e-4d8b-8f27-cae2c537e493:Build:1dc4e278-6813-4749-90b3-0947408ef09b

Detailed Message: TF30065: An unhandled exception occurred.

Web Request Details
    Url: http://tfsapp02:8080/tfs/Osmose/VersionControl/v5.0/repository.asmx [method: POST]
    User Agent: Team Foundation (vsoWorker.exe, 15.105.25910.0, Other, SKU:59)
    Headers: not available
    Path: /tfs/Osmose/VersionControl/v5.0/repository.asmx
    Local Request: False
    Host Address: 10.200.1.50
    User: OSMOSE\TFSSERVICE [authentication type: Federation]

Exception Message: TF10158: The user or group name Colligan, Rob contains unsupported characters, is empty, or too long. (type IllegalIdentityException)
Exception Stack Trace:    at Microsoft.VisualStudio.Services.Identity.IdentityValidation.CheckAccountName(String& accountName)
   at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.ReadIdentities(IVssRequestContext requestContext, IdentitySearchFilter searchFactor, String factorValue, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters, ReadIdentitiesOptions options)
   at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.ReadIdentities(IVssRequestContext requestContext, IdentitySearchFilter searchFactor, String factorValue, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters)
   at Microsoft.TeamFoundation.Framework.Server.IdentityHelper.FindIdentity(IVssRequestContext requestContext, String identityName, Boolean throwOnMissing, Boolean includeInactiveIdentities)
   at Microsoft.TeamFoundation.VersionControl.Server.TfvcIdentityHelper.FindIdentity(IVssRequestContext requestContext, String name)
   at Microsoft.TeamFoundation.VersionControl.Server.CommandCheckIn.ExecuteInternal(Identity owner, String workspaceName, Int32 workspaceVersion, PendingSetType workspaceType, String computer, Workspace localWorkspace, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, Boolean deferCheckIn, Int32 checkInTicket)
   at Microsoft.TeamFoundation.VersionControl.Server.CommandCheckInWorkspace.Execute(String workspaceName, String ownerName, String[] serverItems, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, Changeset info, Boolean deferCheckIn, Int32 checkInTicket)
   at Microsoft.TeamFoundation.VersionControl.Server.TeamFoundationVersionControlService.CheckIn(IVssRequestContext requestContext, String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, Boolean deferCheckIn, Int32 checkInTicket, Boolean returnFailures, PathLength maxClientPathLength)
   at Microsoft.TeamFoundation.VersionControl.Server.Repository5.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, StreamingCollection`1& conflicts, StreamingCollection`1& failures, Boolean deferCheckIn, Int32 checkInTicket, Int32 maxClientPathLength)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="TFS Services" />
    <EventID Qualifiers="0">3000</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-04-22T18:01:04.000000000Z" />
    <EventRecordID>27829</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TFSAPP02.local.osmose.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>TF53010: The following error has occurred in a Team Foundation component or extension:
Date (UTC): 4/22/2017 6:01:04 PM
Machine: TFSAPP02
Application Domain: /LM/W3SVC/2/ROOT/tfs-13-131373509863410586
Assembly: Microsoft.TeamFoundation.Framework.Server, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
Service Host: 1dc4e278-6813-4749-90b3-0947408ef09b (Osmose)
Process Details:
  Process Name: w3wp
  Process Id: 3800
  Thread Id: 3472
  Account name: 35deb4eb-8d0e-4d8b-8f27-cae2c537e493:Build:1dc4e278-6813-4749-90b3-0947408ef09b

Detailed Message: TF30065: An unhandled exception occurred.

Web Request Details
    Url: http://tfsapp02:8080/tfs/Osmose/VersionControl/v5.0/repository.asmx [method: POST]
    User Agent: Team Foundation (vsoWorker.exe, 15.105.25910.0, Other, SKU:59)
    Headers: not available
    Path: /tfs/Osmose/VersionControl/v5.0/repository.asmx
    Local Request: False
    Host Address: 10.200.1.50
    User: OSMOSE\TFSSERVICE [authentication type: Federation]

Exception Message: TF10158: The user or group name Colligan, Rob contains unsupported characters, is empty, or too long. (type IllegalIdentityException)
Exception Stack Trace:    at Microsoft.VisualStudio.Services.Identity.IdentityValidation.CheckAccountName(String&amp; accountName)
   at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.ReadIdentities(IVssRequestContext requestContext, IdentitySearchFilter searchFactor, String factorValue, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters, ReadIdentitiesOptions options)
   at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.ReadIdentities(IVssRequestContext requestContext, IdentitySearchFilter searchFactor, String factorValue, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters)
   at Microsoft.TeamFoundation.Framework.Server.IdentityHelper.FindIdentity(IVssRequestContext requestContext, String identityName, Boolean throwOnMissing, Boolean includeInactiveIdentities)
   at Microsoft.TeamFoundation.VersionControl.Server.TfvcIdentityHelper.FindIdentity(IVssRequestContext requestContext, String name)
   at Microsoft.TeamFoundation.VersionControl.Server.CommandCheckIn.ExecuteInternal(Identity owner, String workspaceName, Int32 workspaceVersion, PendingSetType workspaceType, String computer, Workspace localWorkspace, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, Boolean deferCheckIn, Int32 checkInTicket)
   at Microsoft.TeamFoundation.VersionControl.Server.CommandCheckInWorkspace.Execute(String workspaceName, String ownerName, String[] serverItems, CheckinNotificationInfo checkinNotificationInfo, CheckInOptions2 checkinOptions, Changeset info, Boolean deferCheckIn, Int32 checkInTicket)
   at Microsoft.TeamFoundation.VersionControl.Server.TeamFoundationVersionControlService.CheckIn(IVssRequestContext requestContext, String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, Boolean deferCheckIn, Int32 checkInTicket, Boolean returnFailures, PathLength maxClientPathLength)
   at Microsoft.TeamFoundation.VersionControl.Server.Repository5.CheckIn(String workspaceName, String ownerName, String[] serverItems, Changeset info, CheckinNotificationInfo checkinNotificationInfo, Int32 checkinOptions, StreamingCollection`1&amp; conflicts, StreamingCollection`1&amp; failures, Boolean deferCheckIn, Int32 checkInTicket, Int32 maxClientPathLength)

</Data>
  </EventData>
</Event>`

**Comment by jessehouwing** [comment]
@rdeldad this may be hard to check, but could you try to find this user in the tfs_configuration database, I think you'd be looking for tbl_identity.displayname, and check whether the user name there has any strange whitespace? possibly by converting it to HEX and verifying there are no strange characters in there anywhere?

* https://timscyclingblog.wordpress.com/2012/01/12/sql-server-convert-a-string-into-a-hex-string-and-back-sql-sqlserver/oding/

The identity team is looking to see if there may be trailing whitespace or non-standard whitespace anywhere in the name to be able to exclude that as an option. 

I'm personally wondering what happens when you try to use `tf vc checkin /author:"Lastname, Firstname"` because basically my powershell closely mimics that.

**Comment by jessehouwing** [comment]
Thanks for testing. Published.
