### ISSUE TITLE
Checkin task throws the conflict error.

### ISSUE THREAD

**Issue by ugurcicekfidan** [jessehouwing/vsts-tfvc-tasks#60]
Hi, 
Sometimes checkin task throws the conflict error. Have an idea or workaround?

> 2017-12-08T18:20:13.8998843Z ##[error]System.Management.Automation.MethodInvocationException: **Exception calling "CheckIn" with "1" argument(s): "TF10141: No files checked in: resolve the conflicts and try again." --->** Microsoft.TeamFoundation.VersionControl.Client.CheckinException: TF10141: No files checked in: resolve the conflicts and try again.
2017-12-08T18:20:13.8998843Z    at Microsoft.TeamFoundation.VersionControl.Client.Client.ReportCheckInConflictsFailuresAndThrow(Workspace workspace, CheckinResult checkinResult, Failure[] conflicts, Failure[] failures, Boolean noAutoResolve, Int32 operationId)
2017-12-08T18:20:13.8998843Z    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckInInternal(WorkspaceCheckInParameters parameters, Int32 operationId)
2017-12-08T18:20:13.8998843Z    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.CheckIn(WorkspaceCheckInParameters checkinParameters)
2017-12-08T18:20:13.8998843Z    at CallSite.Target(Closure , CallSite , Object , Object )
2017-12-08T18:20:13.8998843Z    --- End of inner exception stack trace ---
2017-12-08T18:20:13.8998843Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-12-08T18:20:13.8998843Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-12-08T18:20:13.8998843Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-08T18:20:13.8998843Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-08T18:20:13.8998843Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-12-08T18:20:13.9155075Z ##[error]PowerShell script completed with 1 errors.

**Comment by jessehouwing** [comment]
If files are checked in during a build which are also changed during the
build is running, the checkin will fail. Not much you can do about it.

Having the build force-overwrite would probably be bad.

You could use gated checkin and the update shelfset task, that will ensure
sequential processing.
